require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BlackRecordsController do

  # This should return the minimal set of attributes required to create a valid
  # BlackRecord. As you add validations to BlackRecord, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BlackRecordsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all black_records as @black_records" do
      black_record = BlackRecord.create! valid_attributes
      get :index, {}, valid_session
      assigns(:black_records).should eq([black_record])
    end
  end

  describe "GET show" do
    it "assigns the requested black_record as @black_record" do
      black_record = BlackRecord.create! valid_attributes
      get :show, {:id => black_record.to_param}, valid_session
      assigns(:black_record).should eq(black_record)
    end
  end

  describe "GET new" do
    it "assigns a new black_record as @black_record" do
      get :new, {}, valid_session
      assigns(:black_record).should be_a_new(BlackRecord)
    end
  end

  describe "GET edit" do
    it "assigns the requested black_record as @black_record" do
      black_record = BlackRecord.create! valid_attributes
      get :edit, {:id => black_record.to_param}, valid_session
      assigns(:black_record).should eq(black_record)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new BlackRecord" do
        expect {
          post :create, {:black_record => valid_attributes}, valid_session
        }.to change(BlackRecord, :count).by(1)
      end

      it "assigns a newly created black_record as @black_record" do
        post :create, {:black_record => valid_attributes}, valid_session
        assigns(:black_record).should be_a(BlackRecord)
        assigns(:black_record).should be_persisted
      end

      it "redirects to the created black_record" do
        post :create, {:black_record => valid_attributes}, valid_session
        response.should redirect_to(BlackRecord.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved black_record as @black_record" do
        # Trigger the behavior that occurs when invalid params are submitted
        BlackRecord.any_instance.stub(:save).and_return(false)
        post :create, {:black_record => { "name" => "invalid value" }}, valid_session
        assigns(:black_record).should be_a_new(BlackRecord)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        BlackRecord.any_instance.stub(:save).and_return(false)
        post :create, {:black_record => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested black_record" do
        black_record = BlackRecord.create! valid_attributes
        # Assuming there are no other black_records in the database, this
        # specifies that the BlackRecord created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        BlackRecord.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => black_record.to_param, :black_record => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested black_record as @black_record" do
        black_record = BlackRecord.create! valid_attributes
        put :update, {:id => black_record.to_param, :black_record => valid_attributes}, valid_session
        assigns(:black_record).should eq(black_record)
      end

      it "redirects to the black_record" do
        black_record = BlackRecord.create! valid_attributes
        put :update, {:id => black_record.to_param, :black_record => valid_attributes}, valid_session
        response.should redirect_to(black_record)
      end
    end

    describe "with invalid params" do
      it "assigns the black_record as @black_record" do
        black_record = BlackRecord.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BlackRecord.any_instance.stub(:save).and_return(false)
        put :update, {:id => black_record.to_param, :black_record => { "name" => "invalid value" }}, valid_session
        assigns(:black_record).should eq(black_record)
      end

      it "re-renders the 'edit' template" do
        black_record = BlackRecord.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BlackRecord.any_instance.stub(:save).and_return(false)
        put :update, {:id => black_record.to_param, :black_record => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested black_record" do
      black_record = BlackRecord.create! valid_attributes
      expect {
        delete :destroy, {:id => black_record.to_param}, valid_session
      }.to change(BlackRecord, :count).by(-1)
    end

    it "redirects to the black_records list" do
      black_record = BlackRecord.create! valid_attributes
      delete :destroy, {:id => black_record.to_param}, valid_session
      response.should redirect_to(black_records_url)
    end
  end

end
